SDL-0274: add preferred FPS to VideoStreamingCapability
smartdevicelink/sdl_core pull request #3437
Opened 2020-06-15 10:29 UTC by shiniwat

Fixes #3243 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
N/A

### Summary
This PR is for SDL-0274: add preferred FPS to VideoStreamingCapability.

### Changelog
##### Breaking Changes
* N/A

##### Enhancements
* N/A

##### Bug Fixes
* This takes care of sdl_core issue #3243.
Please note that rpc_spec submodule must be updated. I will update the submodule as soon as another PR at https://github.com/smartdevicelink/rpc_spec/pull/229 has been merged.

### Tasks Remaining:
- none

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2020-12-01 16:59 UTC, jordynmackool commented
Hi @shiniwat, this PR should point to the branch of the RPC Spec that contains the changes needed for this feature. 

RPC Spec changes are not merged until the feature has been properly tested with all the required projects and it is confirmed the feature will make it into the slated releases.

Once this PR is updated and tested against the RPC Spec feature branch, please tag me requesting a review.

2021-01-04 15:29 UTC, jordynmackool commented
@shiniwat is this ready for Livio review?

2021-01-05 01:11 UTC, shiniwat commented
Hi @jordynmackool,
While Travis CI seems to fail with "The job exceeded the maximum time limit for jobs, and has been terminated." error, the build works fine on my devbox (Ubuntu 1804). I believe this is ready for Livio review.

2021-01-12 16:21 UTC, jacobkeeler approved these changes

2021-01-12 16:22 UTC, jacobkeeler requested changes
See comments

2021-01-13 06:56 UTC, shiniwat commented on .gitmodules
> +	url = https://github.com/shiniwat/rpc_spec.git
@jacobkeeler, thanks for the review. I have updated the commit hash as well as restoring .gitmodules accordingly.

2021-01-13 13:17 UTC, jacobkeeler approved these changes

2021-02-03 15:07 UTC, jacobkeeler commented
@shiniwat Please update the rpc_spec submodule to the latest `develop` to fix merge conflicts

2021-02-04 14:06 UTC, merged