Bugfix 2808 copy
smartdevicelink/sdl_core pull request #3546
Opened 2020-10-20 18:59 UTC by JackLivio

Updated version of pr #3428

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2020-10-20 22:31 UTC, JackLivio commented
I noticed some atf failure relating on OnEventChange. Deactivate_HMI seems to be crashing core. This fix will need some updates.

2020-10-21 17:29 UTC, JackLivio commented
Crash is fixed, ready for review.

2020-10-23 16:18 UTC, jacobkeeler requested changes
In addition, I think these checks should be in the `hmi_level` function rather than the `max_hmi_level` function

2020-10-23 16:18 UTC, jacobkeeler commented on src/components/application_manager/src/hmi_state.cc
> +  }
```suggestion
  if (HMILevel::INVALID_ENUM == parent_hmi_level()) {
    return parent_hmi_level();
  }
```
This function has a null check for `parent()` when necessary

2020-10-23 16:18 UTC, jacobkeeler commented on src/components/application_manager/src/hmi_state.cc
> +  }
```suggestion
  if (HMILevel::INVALID_ENUM == parent_hmi_level()) {
    return parent_hmi_level();
  }
```
This function has a null check for `parent()` when necessary

2020-10-23 16:18 UTC, jacobkeeler commented on src/components/application_manager/src/hmi_state.cc
> +  }
```suggestion
  if (HMILevel::INVALID_ENUM == parent_hmi_level()) {
    return parent_hmi_level();
  }
```
This function has a null check for `parent()` when necessary

2020-10-23 16:18 UTC, jacobkeeler commented on src/components/application_manager/src/hmi_state.cc
> +  }
```suggestion
  if (HMILevel::INVALID_ENUM == parent_hmi_level()) {
    return parent_hmi_level();
  }
```
This function has a null check for `parent()` when necessary

2020-10-23 18:06 UTC, jacobkeeler commented on src/components/application_manager/src/hmi_state.cc
> +  }
Also should probably be in the `hmi_level` function instead of `max_hmi_level`, same goes for all of these checks

2020-10-23 19:47 UTC, jacobkeeler approved these changes

2020-10-26 14:27 UTC, merged