Configure security level in ini file
smartdevicelink/sdl_core pull request #3681
Opened 2021-04-01 12:46 UTC by VadymLuchko

Fixes  #3664

This PR is **[ready]** for review.

### Risk
This PR makes **[no]** API changes.

### Testing Plan
Check secure connection with SyncProxyTester app 

### Summary
In Ubuntu 20.04, the OpenSSL 1.1.1f library has been modified to use Security Level 2 by default.
With this PR it becomes possible to change the Security Level in .ini file for establish secure connection with some applications that do not support this level.

In details about levels from openssl doc (https://www.openssl.org/docs/man1.1.0/man3/SSL_CTX_get_security_level.html):

Level 0
Everything is permitted. This retains compatibility with previous versions of OpenSSL.

Level 1
The security level corresponds to a minimum of 80 bits of security. Any parameters offering below 80 bits of security are excluded. As a result RSA, DSA and DH keys shorter than 1024 bits and ECC keys shorter than 160 bits are prohibited. All export ciphersuites are prohibited since they all offer less than 80 bits of security. SSL version 2 is prohibited. Any ciphersuite using MD5 for the MAC is also prohibited.

Level 2
Security level set to 112 bits of security. As a result RSA, DSA and DH keys shorter than 2048 bits and ECC keys shorter than 224 bits are prohibited. In addition to the level 1 exclusions any ciphersuite using RC4 is also prohibited. SSL version 3 is also not allowed. Compression is disabled.
...
(there are also levels 3,4,5 )

At this time setting the security level higher than 1 for general internet use is likely to cause considerable interoperability issues and is not recommended. This is because the SHA1 algorithm is very widely used in certificates and will be rejected at levels higher than 1 because it only offers 80 bits of security.

### CLA
- [ ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-04-01 12:48 UTC, VadymLuchko commented
@JackLivio this PR is ready for review

2021-04-01 17:24 UTC, jacobkeeler requested changes

2021-04-01 17:24 UTC, jacobkeeler commented on src/components/security_manager/src/crypto_manager_impl.cc
> +#if OPENSSL_VERSION_NUMBER > OPENSSL1_1_VERSION
```suggestion
#if OPENSSL_VERSION_NUMBER >= OPENSSL1_1_VERSION
```

2021-04-01 21:46 UTC, VadymLuchko commented on src/components/security_manager/src/crypto_manager_impl.cc
> +#if OPENSSL_VERSION_NUMBER > OPENSSL1_1_VERSION
@jacobkeeler Done

2021-04-06 15:46 UTC, jacobkeeler approved these changes

2021-04-06 15:48 UTC, merged