Clear Parent Reference to Begin State When it is Erased
smartdevicelink/sdl_core pull request #3769
Opened 2021-09-08 17:57 UTC by iCollin

Fixes https://github.com/smartdevicelink/sdl_core/issues/3768

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Issue Reproduction Steps
https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2578
Additional ATF Test Scripts updates to come

### Summary
When cancelling temp state and temp state is `hmi_states.begin()`, we must check if the next element holds reference to state we are deleting in parent property and remove it if so.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-09-08 18:36 UTC, jacobkeeler requested changes

2021-09-08 18:36 UTC, jacobkeeler commented on src/components/application_manager/src/application_state.cc
> +    }
```suggestion
    if (hmi_states.end() != next) {
      HmiStatePtr next_state = *next;
      next_state->set_parent(nullptr);
    }
```
For the sake of consistency

2021-09-08 18:36 UTC, jacobkeeler commented on src/components/application_manager/src/application_state.cc
> +  if (hmi_states.begin() == it && hmi_states.size() > 1) {
```suggestion
  if (hmi_states.begin() == it) {
```
The checks within this statement should cover this. We don't want the `else` case triggering if `size() == 1` (though in practice this shouldn't happen)

2021-09-09 18:15 UTC, JackLivio approved these changes

2021-09-09 18:25 UTC, merged