Cyclic UpdateDeviceList and UpdateAppList in case device is connected
smartdevicelink/sdl_core pull request #3835
Opened 2021-12-14 12:59 UTC by RomanReznichenkoLuxoft

Fixes #[3346](https://github.com/smartdevicelink/sdl_core/issues/3346)

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Summary
Core runs scripts for thread delegates at intervals. Bluetooth is constantly running an event of type ON_DEVICE_LIST_UPDATED, but we do not receive new devices to connect. So I added a check to abort the script with an empty device list.
When we connect the device, it acquires the status of connected, but we only checked the response of the ConnectDevice function. Because of this, after connecting the device, we constantly run an event of type ON_CONNECTION_STATUS_UPDATED. UpdateAppList is called when processing this event.

### CLA
- [ ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-12-23 17:56 UTC, RomanReznichenkoLuxoft commented
@jordynmackool This PR is ready for Livio review

2022-01-10 17:13 UTC, jacobkeeler requested changes

2022-01-12 15:18 UTC, LitvinenkoIra commented
@jacobkeeler  We are doing regression testing right now, I’ll let you know when this PR is ready for re-review

2022-01-13 12:10 UTC, LitvinenkoIra commented
@jacobkeeler This PR is ready for review.

2022-01-13 19:59 UTC, jacobkeeler approved these changes

2022-01-13 20:28 UTC, merged