Fix/Adjust PTS content length for newline string
smartdevicelink/sdl_core pull request #3913
Opened 2022-04-26 14:19 UTC by ShobhitAd

Fixes #3912 

This PR is **not ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Test Suite and ATF regression

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2022-04-27 14:30 UTC, jacobkeeler requested changes

2022-04-27 14:30 UTC, jacobkeeler commented on src/appMain/sample_policy_manager.py
> +    content_length = len(data) - data.count('\\n')
pretty sure this should just be done for all escape characters
```suggestion
    content_length = len(data) - data.count('\\')
```

2022-04-27 14:30 UTC, jacobkeeler commented on src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/on_system_request_notification.cc
> +    } else if (pt_string[i] == 'n' && i > 0 && pt_string[i - 1] == '\\') {
Seems that the solution could be more generic here as well, something like
```
    if (pt_string[i] == '\"') {
      result += '\\';
    }
    else if (pt_string[i] == '\\') {
      result += '\\';
      --result_length;  // contentLength is adjusted for the additional escape
                        // character added before the newline string
    } else if (pt_string[i] == '\n') {
      --result_length;  // contentLength is adjusted when this character is
                        // not copied to result.
      continue;
    }
```

2022-05-04 20:47 UTC, JackLivio approved these changes

2022-05-27 14:15 UTC, merged