Make shared pointer atomic
smartdevicelink/sdl_core pull request #3920
Opened 2022-06-02 13:54 UTC by VladSemenyuk

Fixes #3871

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Atf scripts

### Summary
This is actually a template specialization proposed here:
https://en.cppreference.com/w/cpp/memory/shared_ptr/atomic2

If multiple threads of execution access the same std::shared_ptr object without synchronization and any of those accesses uses a non-const member function of shared_ptr then a data race will occur unless all such access is performed through an instance of std::atomic<<std::shared_ptr>>

To avoid these data races, shared pointers itself were made atomic

### CLA
- [ ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2022-06-02 13:55 UTC, VladSemenyuk commented
@theresalech this PR is ready for Livio review

2022-06-21 20:26 UTC, ShobhitAd requested changes

2022-06-21 20:26 UTC, ShobhitAd commented on src/components/utils/test/atomic_object_test.cc
> +  EXPECT_EQ(false, static_cast<bool>(flag));
Might be worth adding another case with a pointer or non primitive type (like `sync_primitives::Atomic<std::string>`)

2022-06-21 20:26 UTC, ShobhitAd commented on src/components/utils/test/atomic_object_test.cc
> +
Might need to expand the unit tests to test the implementation of the Atomic class. Perhaps a case with multiple threads with one setting the value and another trying to access it

2022-06-28 11:04 UTC, VladSemenyuk commented on src/components/utils/test/atomic_object_test.cc
> +  EXPECT_EQ(false, static_cast<bool>(flag));
Done

2022-06-28 11:05 UTC, VladSemenyuk commented on src/components/utils/test/atomic_object_test.cc
> +
I don't see a good solution for simultaneous access to the atomic object from different threads in unit test.

2022-06-29 21:14 UTC, ShobhitAd approved these changes

2022-06-29 21:14 UTC, merged