Fix/Reset sending type on ResetGlobalProperties
smartdevicelink/sdl_core pull request #3937
Opened 2022-07-18 14:25 UTC by ShobhitAd

Fixes #3931

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Submitted ATF test PR for defect

### Summary
Implements a `OnResetGlobalPropertiesReceived` method in the help_prompt_manager. When a ResetGlobalProperties request is received from an application the sending_type_ will be reset based on the global property ids in the request

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2022-07-25 19:54 UTC, jacobkeeler requested changes
Something I think we missed with https://github.com/smartdevicelink/sdl_core/pull/3916/files

I think that the values set after the reset should match up with the ones generated by `help_prompt_manager.cc` if possible, currently they differ slightly because it uses the MessageHelper function rather than the help prompt manager.

2022-07-28 15:47 UTC, ShobhitAd commented
> Something I think we missed with https://github.com/smartdevicelink/sdl_core/pull/3916/files
> 
> I think that the values set after the reset should match up with the ones generated by `help_prompt_manager.cc` if possible, currently they differ slightly because it uses the MessageHelper function rather than the help prompt manager.

I tried that on my end but I'm not sure if the items returned for ResetGlobalProperties and AddCommand should match. 

The `MessageHelper::CreateAppVrHelp` function returns vrHelpItems [appName + VR synonyms + VR Commands] while `HelpPromptManagerImpl::GenerateVrItems` only returns [VR Commands]. The MessageHelper function seems more appropriate for ResetGlobalProperties but if it were combined with the HelpPromptManager function it would return [appName + VR synonyms + VR Commands] even after an AddCommand. 

I guess we combine it in such a way that the function would return [appName + VR synonyms] if no VR Commands or maybe just rename the MessageHelper function to `CreateDefaultAppVrHelp` since that function is currently only used for ResetGlobalProperties

2022-07-28 15:51 UTC, ShobhitAd commented
Found another issue while creating ATF tests to test the PR. If an app sends ResetGlobalProperties with **only** `"HELPPROMPT"` core sends a response with `{ success = false, resultCode = "SUCCESS"}`. This seems to be caused due to how the responses are combined in `RequestFromMobileImpl::PrepareResultForMobileResponse` (https://github.com/smartdevicelink/sdl_core/blob/develop/src/components/application_manager/src/commands/request_from_mobile_impl.cc#L664)

Fixed in https://github.com/smartdevicelink/sdl_core/pull/3937/commits/b9750e0d91249e318563723d8f3053bf80781ce0

2022-07-28 20:56 UTC, jacobkeeler commented
Given the original intent of [SDL-0122](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0122-New_rules_for_providing_VRHelpItems_VRHelpTitle.md) (providing standard generated help information for an app when it does not provide its own), I think we should use the same format for all cases where the app does not have these fields explicitly set (which includes when they are reset).

Personally I think that we should just make some of the `HelpPromptManager` methods (such as `GenerateVrItems`) public and just use those instead of the existing MessageHelper functions, they seem to be outdated with the implementation of SDL-0122 and should probably just be removed.

2022-08-04 18:48 UTC, jacobkeeler approved these changes

2022-08-04 19:20 UTC, merged